---
title: Zonnestelsel
hero_image: images/banner.png
description: Leer Python dictionaries kennen door een model van het zonnestelsel te maken
meta_title: Python programmeerprojecten voor kinderen en tieners | Zonnestelsel
meta_description: Leer Python met de programmeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Maak kennis met Python dictionaries door een model van het zonnestelsel te maken.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-13"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Maak een dictionary
  - 
    title: Maak Mercurius
    completion:
      - engaged
  - 
    title: Maak Venus
  - 
    title: Maak aarde
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
