---
title: Solar system
hero_image: images/banner.png
description: Get to know Python dictionaries by creating a model of the solar system
meta_title: Python coding projects for kids and teens | Solar system
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Get to know Python dictionaries by creating a model of the solar system.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-13"
steps:
  - title: You will make
  - title: Create a dictionary
  - title: Make Mercury
    completion:
      - engaged
  - title: Make Venus
  - title: Make Earth
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project